name: Check shell scripts

on:
  push:
    paths:
      - *.sh
  pull_request_target:
    paths:
      - *.sh

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    container:
      image: docker.io/ubuntu:22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install shellcheck
        run: apt update && apt install -y shellcheck && shellcheck --version

      - name: Check install script
        run: shellcheck --severity=info *.sh