name: Check shell scripts

on:
  push:
    branches:
      - webv2
  pull_request:
    branches:
      - webv2

defaults:
  run:
    shell: bash

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    container:
      image: docker.io/ubuntu:22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install shellcheck
        run: apt update && apt install -y shellcheck bash && shellcheck --version

      - name: Check shell scripts
        run: ls **/*.sh && shellcheck --severity=info **/*.sh
